### ISSUE TITLE
https://github.com/OpenZeppelin/ctf-infra lands to a 404 page

### ISSUE THREAD

**Issue by Strapontin** [OpenZeppelin/ctf-2024#3]
The "ctf-infra" link lands to a 404 page. Is it public ?

https://github.com/OpenZeppelin/ctf-infra

**Comment by cairoeth** [comment]
The repo itself is not public yet, but you can find the package [here](https://github.com/orgs/OpenZeppelin/packages/container/package/ctf-infra).

**Comment by Strapontin** [comment]
Thank you ! Thanks as well to you and all the team for the hackaton :D

**Comment by cairoeth** [comment]
@Strapontin the repo is public now!
