### ISSUE TITLE
how to wait exactly two blocks

### ISSUE THREAD

**Issue by Azleal** [OpenZeppelin/ctf-2024#4]
how to wait exactly two blocks [here](https://github.com/OpenZeppelin/ctf-2024/blob/0527d0e1ea6d729faf753057af6f24cc89584b4e/spacebank/challenge/project/script/Solve.s.sol#L77)

**Comment by cairoeth** [comment]
@Azleal you can do it manually with that Foundry script or by setting up a script separately that monitors the blocks.

**Comment by luckybool1020** [comment]
> Foundry script

Foundry script  seems can't wait blocks
