### ISSUE TITLE
The docker of alienspaceship challenge seems have some problem.when I launch new instance , and call the ALIENSPACESHIP() , get message: execution revertedof challenge contract, 

### ISSUE THREAD

**Issue by luckybool1020** [OpenZeppelin/ctf-2024#5]
<img width="702" alt="image" src="https://github.com/OpenZeppelin/ctf-2024/assets/16422202/9eecd55d-3d24-47e4-bd3e-e567bcc58d0b">

**Comment by cairoeth** [comment]
@luckybool1020 the function selector you are using is wrong -- should be `"ALIENSPACESHIP()(address)"`, so: `cast call CHALLENGE_CONTRACT "ALIENSPACESHIP()(address)" --rpc-url RPC_URL`
