### ISSUE TITLE
the challenge of dutch,when i deploy the contract get the message:vyper.exceptions.VersionException: line 1:0 Version specification \"~=0.3.10\" is not compatible with compiler version \"0.4.0b4\

### ISSUE THREAD

**Issue by luckybool1020** [OpenZeppelin/ctf-2024#6]
python: 3.12
vyper:0.4.0b4
snekmate:0.0.5

<img width="910" alt="image" src="https://github.com/OpenZeppelin/ctf-2024/assets/16422202/2b7389c6-e628-4807-99b9-b85f5efed8c5">

**Comment by cairoeth** [comment]
@luckybool1020 how are you running the challenge? if you run it via [ctf-infra](https://github.com/OpenZeppelin/ctf-infra), you shouldn't get any errors. [This](https://github.com/blocksecteam/Ethernaut_2024_phalcon) might be easier to use.

**Comment by luckybool1020** [comment]
> @luckybool1020 how are you running the challenge? if you run it via [ctf-infra](https://github.com/OpenZeppelin/ctf-infra), you shouldn't get any errors. [This](https://github.com/blocksecteam/Ethernaut_2024_phalcon) might be easier to use.

I don't run it via ctf-infra,  I run it on local anvil. use forge script ./script/deploy.s.sol

**Comment by cairoeth** [comment]
@luckybool1020 in that case, it's a problem on your setup -- i recommend using the same versions we have on the docker: Python 3.11.6 and vyper 0.4.0b5
